services:
  redis:
    image: bitnami/redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  redisinsight:
    image: redislabs/redisinsight:latest
    volumes:
      - redisinsight:/db
    ports:
      - "8001:8001"

volumes:
  redisinsight: